project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "assignments/*.ipynb"

website:
  title: "Understanding Uncertainty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: assignments.qmd
        text: Assignments
    right:
      - icon: github
        href: https://github.com/jrudoler-teaching/understanding-uncertainty
      - icon: twitter
        href: https://twitter.com/jrudoler
  sidebar:
      style: "floating"
      search: true
      contents:
        - text: "Lecture 00"
          href: notebooks/lecture-00.ipynb
        - text: "Lecture 01"
          href: notebooks/lecture-01.ipynb
        - text: "Lecture 02"
          href: notebooks/lecture-02.ipynb
        - text: "Lecture 03"
          href: notebooks/lecture-03.ipynb
        - text: "Lecture 04"
          href: notebooks/lecture-04.ipynb
        - text: "Lecture 05"
          href: notebooks/lecture-05.ipynb
        - text: "Lecture 06"
          href: notebooks/lecture-06.ipynb
        - text: "Lecture 07"  
          href: notebooks/lecture-07.ipynb
        - text: "Lecture 08"
          href: notebooks/lecture-08.ipynb
        - text: "Lecture 09"
          href: notebooks/lecture-09.ipynb
        - text: "Lecture 10"
          href: notebooks/lecture-10.ipynb
        - text: "Lecture 11"
          href: notebooks/lecture-11.ipynb
        - text: "Lecture 12"
          href: notebooks/lecture-12.ipynb
  page-navigation: true

format:
  html:
    theme: 
      dark: darkly
      light: minty
    css: styles.css
    toc: true



