project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "notebooks/*-slides.qmd"
    - "assignments/*.ipynb"

website:
  title: "Understanding Uncertainty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: assignments.qmd
        text: Assignments
    right:
      - icon: github
        href: https://github.com/jrudoler-teaching/understanding-uncertainty
  sidebar:
      style: "floating"
      search: true
      contents:
        - text: "Lecture 00 Notes"
          href: notebooks/lecture-00.ipynb
        - text: "Lecture 00 Slides"
          href: notebooks/lecture-00-slides.qmd
  page-navigation: true

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



